services:
  # Main PizzaOrderingSystem service
  pizza-ordering-system:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - pizza-network

  # ProductManagementSystem service
  product-management-system:
    build:
      context: ./ProductManagementSystem
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - APP_PORT=8080
      - DB_NAME=productdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/productdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres
    networks:
      - pizza-network

  # PostgreSQL database for ProductManagementSystem
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=productdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - pizza-network

networks:
  pizza-network:
    driver: bridge

volumes:
  postgres-data:
